# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f26d6d4f0f6edc6bc0f8759f93da0e5c83b1fe198b9442f1b5ff896f184fd4ac234c01daa9338637d4922fdb77dd3e26cf754b23facbfdbfab98a0263bf45f1f

test:
  secret_key_base: 09cd6929c6b56e492718734d82921458c9917c884dcac919605ce87db6a3d00915081e27c39b74cabe763e97d6778decd51b7547b70c5384ded43fcbb54f7844

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
